/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    idea
    java
    id("org.springframework.boot") version "2.5.3"
    id("io.spring.dependency-management") version "1.0.10.RELEASE"
    id("org.sonarqube") version "3.0"

}


repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()

    maven {
        url = uri("https://maven.pkg.github.com/InstaCode/*")
    }
}

dependencies {
    implementation("io.rest-assured:rest-assured:4.4.0")
    implementation("org.springframework.cloud:spring-cloud-config-server:2.2.8.RELEASE")
    implementation("org.springframework.cloud:spring-cloud-starter-eureka:1.4.7.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.5.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.2")
    testImplementation("org.junit:junit-bom:5.8.0-M1")
}

group = "io.instacode.automation"
version = "1.0-SNAPSHOT"
description = "InstaCode Microservices Config Server"
java.sourceCompatibility = JavaVersion.VERSION_11



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
